### ISSUE TITLE
Failed opening. Most probably a sandbox issue. Trying something different.

### ISSUE THREAD

**Issue by shuxiao9058** [stefanesser/dumpdecrypted#12]
```
[+] detected 32bit ARM binary in memory.
[+] offset to cryptid found: @0x53a78(from 0x53000) = a78
[+] Found encrypted data at address 00004000 of length 2490368 bytes - type 1.
[+] Opening /private/var/mobile/Containers/Bundle/Application/2B3C550D-FAA1-4C2B-A85B-FCA241FA16BA/my.app/my for reading.
[+] Reading header
[+] Detecting header type
[+] Executable is a FAT image - searching for right architecture
[+] Correct arch is at offset 16384 in the file
[+] Opening MobileTicket.decrypted for writing.
[-] Failed opening. Most probably a sandbox issue. Trying something different.
[+] Opening /private/var/mobile/Containers/tmp/my.decrypted for writing.
[-] Failed opening: Operation not permitted
```

failed to decrypt the app, the device is iPhone 4S, iOS 8.4.

**Comment by hotogwc** [comment]
@shuxiao9058 Hi Bro,how do you solve this? I encountered the same issue.Please help. Thanks

**Comment by mail2chensh** [comment]
@shuxiao9058 Hi Bro,how do you solve this? I encountered the same issue.Please help. Thanks

**Comment by mail2chensh** [comment]
@hotogwc  Hi Bro,how do you solve this? I encountered the same issue.Please help. Thanks

**Comment by shuxiao9058** [comment]
@mail2chensh  you must do it under the application's data directory, because security of the sanbox to ios.

**Comment by mail2chensh** [comment]
@shuxiao9058 I do it under the document directory,but it still operation no permitted. but when I dump other apps,it work! so I think maybe some apps will have this problem. At last i create the decrypted file manual, and it can work continue.

**Comment by TLHorse** [comment]
> @mail2chensh you must do it under the application's data directory, because security of the sanbox to iOS.

I tried chmod 777 and su root, but operation not permitted. then I saw your comment.
What if an app hasn't got a data directory?
