### ISSUE TITLE
unknown environment variable: DYLD_INSERT_LIBARIES

### ISSUE THREAD

**Issue by 1905796135** [stefanesser/dumpdecrypted#27]
root# DYLD_INSERT_LIBARIES=dumpdecrypted.dylib /var/containers/Bundle/Application/4C7D2442-98A2-471F-AACE-964956B50EFE/XinRen.app/XinRen
dyld: warning, unknown environment variable: DYLD_INSERT_LIBARIES
Abort trap: 6

iPhone6, iOS12.4.4, macOS Catalina 10.15.4, xcode11.5

**Comment by AgoniNemo** [comment]
@1905796135  解决了吗兄弟
