### ISSUE TITLE
dumpdecrypted.dylib: missing LC_DYLD_INFO load command

### ISSUE THREAD

**Issue by yufanghui** [stefanesser/dumpdecrypted#30]
dumpdecrypted.dylib: missing LC_DYLD_INFO load command

**Comment by yufanghui** [comment]
should modify the Makefile

**Comment by feihuang89** [comment]
> should modify the Makefile

@yufanghui how to modify?

**Comment by tianxiawoyougood** [comment]
@yufanghui how to modify?
